site_name: My CTF Writeups

theme:
  name: material
  icon:
    logo: fontawesome/regular/flag
  palette:

    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode

    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
      primary: teal
      accent: indigo

    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Switch to system preference
      primary: amber
      accent: amber
  features:
    - navigation.tabs
    - navigation.tabs.sticky

markdown_extensions:
  - attr_list
  - md_in_html
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

nav:
  - Home: README.md
  - TryHackMe:
    - Overwiew: tryhackme/README.md
    - Valley: tryhackme/valley/README.md
    - RootMe: tryhackme/rootme/README.md
    - Cheese CTF: tryhackme/cheese-ctf/README.md
    - Agent Sudo: tryhackme/agent-sudo/README.md
    - Startup: tryhackme/startup/README.md
  - FCSC:
    - Overwiew: fcsc/README.md
    - Petite Frappe: fcsc/petite-frappe/README.md
    - Layer Cake: fcsc/layer-cake/README.md
    - Meme Generator: fcsc/meme-generator/README.md
    - CryptoLocker v1: fcsc/cryptolocker-v1/README.md
  - UnitedCTF:
    - Overwiew: unitedctf/README.md
    - ARPacadabra: unitedctf/arpacadabra/README.md
  - CryptoHack:
    - Overwiew: cryptohack/README.md
    - JSON in JSON: cryptohack/json-in-json/README.md
